### ISSUE TITLE
deployment problem

### ISSUE THREAD

**Issue by saxon17** [Deathangel908/djangochat#10]
![image](https://user-images.githubusercontent.com/7868631/39745336-890c435c-52d9-11e8-94a1-102fc5ec05a1.png)

Hi， i followed your instrucion  step by step, while come to this  issue above.
I change the version to  '2.0/2.1/3.0'  all  print error. did you see this before.
I try different version docker-compose  inlude yours but in vain.

**Comment by akoidan** [comment]
Hi, you're seeing this error because your docker doesn't support  **version: '2.3'** I specified in `docker-compose.yml`. I used this exact version, because only 2.3 supports `healthcheck` and `condition: service_healthy`. Which operation system are you using and how did you install docker?

**Comment by saxon17** [comment]
latest docker-compose(1.21) solved this probelms. thanks！
keeping eyes on this nice project.

**Comment by saxon17** [comment]
![image](https://user-images.githubusercontent.com/7868631/39847820-3aac796c-5436-11e8-861b-b41f0e3e61fc.png)
next problem 
"bash download_content.sh  all"

is there any way more easier to deploy  OR  develop this proj? T T


  operation system 
Linux version 3.10.0-514.26.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Jul 4 15:04:05 UTC 2017

**Comment by akoidan** [comment]
Are you using docker? 
 -  Using docker shouldn't cause this issue, and you do **NOT** need execute `bash download_content.sh all`. All required steps are specified in https://github.com/Deathangel908/djangochat/#via-docker . There are only 3 of them, I guess this can't be simplified further.
 - If you're not using docker you should export `PYCHAT_CONFIG` variable as specified in  https://github.com/Deathangel908/djangochat/#archlinux . Execute `export PYCHAT_CONFIG=local`

django expects this variable to be present in global variables while executing scripts.

If you want to contribute to this project you need to setup [Development environment](https://github.com/Deathangel908/djangochat#development-setup) instead of docker. I'm going to upload video guide on youtube if steps are not clear. If you find this guide complicated you can also fork the project, edit README.md and create pull request back.

**Comment by saxon17** [comment]
I would like to  follow your video guide .. Expolring by my self may cause more problems.  Hope you can make a more cleare development-evn deployment video on youtube  . An auto deployment shell script  will be more helpful.  Thanks for your answear and help

**Comment by akoidan** [comment]
I added new docker builds. You can run image with a single command `docker run -p 443:443 deathangel908/pychat:test` that shouldn't cost you any problems. Check out [build-docker](https://github.com/Deathangel908/pychat#build-docker) section in readme.

I think with that being said I can close this issue
