### ISSUE TITLE
Logo Proposal for Djangochat

### ISSUE THREAD

**Issue by area55git** [Deathangel908/djangochat#11]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project Djangochat.

I will be pleased to collaborate with you.

**Comment by akoidan** [comment]
Hi, thank you for your offer. I'll be glad you to contribute to this project.

**Comment by area55git** [comment]
Perfect..! I am very enthusiastic to design a Logo for your project.
If you have some ideas, suggestions as to style or colors would be great to be able to start.

**Comment by akoidan** [comment]
If you open [pychat.org](https://pychat.org) you'll see that chat is designed using some colors, the logo could use them.
![image](https://user-images.githubusercontent.com/1336703/40037666-1ef89e8c-5817-11e8-98b3-32e92d0f1946.png)
Also the logo could be present on site favicon (icon on the browser tab). This image is small, so small version of the logo should accommodate.

Also as chat supports many features (video calls/peer to peer file sending/screen share/painter) the logo could depict those. The whole idea about chat is to give companies/people open source project that they could run on their servers instead of saas like [slack](https://slack.com/). I guess this idea makes this chat unique. So logo could get some idea of it.

**Comment by area55git** [comment]
Hi @Deathangel908 This is my proposal for the logo of your project Djangochat.

[![LOGO_PROPOSAL_FOR_DJANGOCHAT.jpg](https://s31.postimg.cc/5ats7y60b/LOGO_PROPOSAL_FOR_DJANGOCHAT.jpg)](https://postimg.cc/image/6d3yqhotj/)

If you like it I will send you pull request
or if you like another color or another logo I can make it for you

**Comment by akoidan** [comment]
Hi, I like the logos. You could change `djangochat` to `pychat` and make a pull request with vectors assets and put them in [chat/static/images](/Deathangel908/pychat/tree/master/chat/static/images). I will put them in readme and logo.

**Comment by area55git** [comment]
With the name change this option works best for your project, don´t you think?

[![LOGO_PROPOSAL_FOR_DJANGOCHAT.jpg](https://s31.postimg.cc/806324owb/LOGO_PROPOSAL_FOR_DJANGOCHAT.jpg)](https://postimg.cc/image/68d4785jb/)

**Comment by akoidan** [comment]
Yeah, the short name looks much better

**Comment by area55git** [comment]
# [FILE DOWNLOAD](https://drive.google.com/open?id=1loxDpgzfn-Mtj6Wrd7dwrvq1rw5G8OQ7)

[![DERECHOS.jpg](https://s31.postimg.cc/4gwjv5gkr/DERECHOS.jpg)](https://postimg.cc/image/ta63vszl3/)

This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).

**Comment by area55git** [comment]
Hi @Deathangel908, did you check the files?

**Comment by akoidan** [comment]
Yes, thanks a lot for your contribution, I just have so few time right now I can't proceed pulling it. I hope I'm going to have some free time in next couple days, mb tomorrow.

**Comment by akoidan** [comment]
I have added the logo, I also wanna add other icons to chat itself, but I got to think where I should put them. Should I also attach license somewhere?

**Comment by area55git** [comment]
I am new to github, but I think that you should place the license.

What icons do you need ?, I can do them and send them in SVG format

**Comment by akoidan** [comment]
I guess I put icons in some folder and put LICENSE FILE there or link to the site you pasted.
